### ISSUE TITLE
Add scaling per texture for U3M 1.1

### ISSUE THREAD

**Issue by vizoomartin** [vizoogmbh/u3m#10]
The suggestion came up to add a scaling factor per texture, so that for example artworks/prints can be scaled independently of the "base" material. 

Scaling currently is not possible in the u3m format, unless we artificially increase/decrease the physical size of width & height, which would corrupt the "original" information.

So for the release of U3M schema 1.1 (which is not scheduled yet, probably later in 2019), we could add:

- a u & v factor to each image's "repeat" parameter
```
"image": {
	"dpi": 1005.0752688172042,
	"height": 2.9937999999999998,
	"path": "textures/0005_Houndstooth_ALPHA.jpg",
	"repeat": {
		"mode": "normal",
		"rotation": 0,
		"scale":{
			"u":1.0,
			"v":1.0
		}
	},
	"width": 3.0983000000000001
},
```

- and a global uv scale. That could be very beneficial for clients using a normed UV scale for their geometries, to make sure u3m files are scaled correctly. 

```
"front":{
	"global_scale":{
		"u":10.0 //in centimeters
		"v":10.0 //in centimeters
	....
```

**Comment by malkosh** [comment]
My 2 cents as we have specifically these same requirements

-We typically only need an independent scale controller for the print on top of the full materials. In some cases it replaces existing color maps and in others adds on top. IN fact in reality, it should be another layer all together depending on the print execution. custom is likely the way to go, but also keep in mind later on, layered materials will need this.

-The UV scale is also something we use, we base our real time engine on the assumption that UV 0-1 space is actually 50cm. BUT I also agree that's software dependent. We build custom rigs inside of the MODO presets and expose those for users to define that 0-1 scale.
