### ISSUE TITLE
Material color name

### ISSUE THREAD

**Issue by GalKatzir** [vizoogmbh/u3m#20]
I open this issue to discuss to add color name to the u3m

As I can see there is two places that this new field can be.
1) color_rgb
```
{
  "constant": {"r": 0.53, "g": 0.8, "b": 0.92, "name" : "SkyBlue",},
  "texture": null
}
```
2) texture_and_color
```
{
  "constant": {"r": 0.53, "g": 0.8, "b": 0.92},
  "color_name" : "SkyBlue",
  "texture": null
}
```

**Comment by vizoomartin** [comment]
As discussed, colors are very company specific (so this information should be in Custom section)
