### ISSUE TITLE
Blender importer bug

### ISSUE THREAD

**Issue by ELSECorp** [vizoogmbh/u3m#8]
The Blender importer does not seem to build the shader network according to the U3M schema specifications.

For example, in the material PinkGlitter_meshfabric:

```
"roughness":
{
	"constant": 1,
	"texture":
	{
		"factor": 0.69999999999999996,
		"image":
		{
			"dpi": 400,
			"height": 7.0929500000000001,
			"path": "textures/PinkGlitter_meshfabric_ROUGH.jpg",
			"repeat": null,
			"width": 11.607800000000001
		},
		"offset": 0
	}
}, 
```

The relevant part of the shader network is:

![network](https://user-images.githubusercontent.com/44395250/48909612-099e9080-ee6e-11e8-8824-7668ecd4deb6.png)

According to the specifications, the color from the texture should be multiplied (default operation of the roughness element) by the factor, whereas in the built shader it is not.

**Comment by vizoomartin** [comment]
Thank you for the feedback!
We are working on the plugin to support the full u3m material - will keep everyone updated.

**Comment by RenateOnVizoo3d** [comment]
Please find the new blender plugin [here](https://customers.vizoo3d.com/wp-content/uploads/2019/01/Blender_U3M_addon_v0.0.9.zip).

Use this Plugin to load and save U3M materials in Blender. 
To install the add-on for Blender go to user preferences, select the add-on tab and install the add-on from this zip file. Activate the add-on and then save your preferences.
In Blender go to File -> Import -> Unified 3D Material (.u3m).
Blender adds a U3M workspace tab. In there you will find a U3M Editor and a render tool.
